title: Jared Boyer
email: jaredb@mit.edu
description: >-
  See my resume here: link

theme: minima

# github_username: jaredbmit
# linkedin_username: jared-boyer-4

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  jaredbmit
    linkedin: jared-boyer-4a5b44201
    gitlab:
     - username: jaredbmit
       instance: gitlab.com

plugins:
 - jekyll-feed
 - jekyll-seo-tag
