title: Jared Boyer
email: jaredb@mit.edu
description: >-

markdown: GFM

theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  jaredbmit
    linkedin: jared-boyer-4a5b44201
    gitlab:
     - username: jaredbmit
       instance: gitlab.com

header_pages:
  - about.md
  - research.md
  - projects.md
  - publications.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
